#### 1.	Write a Python Program to Add Two Matrices?


In [9]:
import numpy as np

def matrix_add(a,b):
    return np.add(a,b)

In [21]:
r1 = int(input("Enter the number of rows for first matrix: "))
c1 = int(input("Enter the number of columns for first matrix: "))
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
a = np.array(entries).reshape(r1, c1)

r2 = int(input("Enter the number of rows for second matrix: "))
c2 = int(input("Enter the number of columns for second matrix: "))
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
b = np.array(entries).reshape(r2, c2)

try:
    res=matrix_add(a,b)
    print('Result of two matrix addition is : ',res)
except Exception as e:
    print(e)

Enter the number of rows for first matrix: 2
Enter the number of columns for first matrix: 2
Enter the entries in a single line (separated by space): 
8 9 6 3
Enter the number of rows for second matrix: 2
Enter the number of columns for second matrix: 2
Enter the entries in a single line (separated by space): 
12 6 3 8
Result of two matrix addition is :  [[96 54]
 [18 24]]


#### 2.	Write a Python Program to Multiply Two Matrices?


In [27]:
import numpy as np

def matrix_mul(a,b):
    return np.dot(a,b)

In [28]:
r1 = int(input("Enter the number of rows for first matrix: "))
c1 = int(input("Enter the number of columns for first matrix: "))
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
a = np.array(entries).reshape(r1, c1)

r2 = int(input("Enter the number of rows for second matrix: "))
c2 = int(input("Enter the number of columns for second matrix: "))
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
b = np.array(entries).reshape(r2, c2)

try:
    res=matrix_mul(a,b)
    print('Result of two matrix multiplication is : ',res, end='')
except Exception as e:
    print(e)

Enter the number of rows for first matrix: 3
Enter the number of columns for first matrix: 2
Enter the entries in a single line (separated by space): 
2 3 4 2 10 9
Enter the number of rows for second matrix: 2
Enter the number of columns for second matrix: 3
Enter the entries in a single line (separated by space): 
5 8 6 10 2 3
Result of two matrix multiplication is :  [[ 40  22  21]
 [ 40  36  30]
 [140  98  87]]

#### 3.	Write a Python Program to Transpose a Matrix?


In [29]:
def trans_matrix(a):
    return np.transpose(a)

In [30]:
r = int(input("Enter the number of rows: "))
c = int(input("Enter the number of columns: "))
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
a = np.array(entries).reshape(r, c)

trans_matrix(a)

Enter the number of rows: 3
Enter the number of columns: 2
Enter the entries in a single line (separated by space): 
5 8 6 10 2 3


array([[ 5,  6,  2],
       [ 8, 10,  3]])

#### 4.	Write a Python Program to Sort Words in Alphabetic Order?


In [64]:
def sort_words(words):
    word=words.split()
    word.sort()
    for i in word:
        print(i)

In [67]:
s="Python Program to Sort Words in Alphabetic Order"
print('Sorted words are :')
sort_words(s)

Sorted words are :
Alphabetic
Order
Program
Python
Sort
Words
in
to


#### 5.	Write a Python Program to Remove Punctuation From a String?


In [81]:
import re
def remove_punct(s):
    res=re.sub(r'[^\w\s]','',s)
    return res

In [83]:
s='what is!! 41 doing ,; here?'
remove_punct(s)

'what is 41 doing  here'